#!/bin/sh
set -ou pipefail

# Copyright (c) Erlimar Silva Campos. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

cp $PWD/.crosshrc $HOME/.crosshrc
cp $PWD/.bashrc $HOME/.bashrc
cp $PWD/.zshrc $HOME/.zshrc

echo "Dot files successfully exported!"

