#!/bin/sh
set -ou pipefail

# Copyright (c) Erlimar Silva Campos. All rights reserved.
# Licensed under the Apache License, Version 2.0. More license information in LICENSE.txt.

cp $HOME/.crosshrc $PWD/.crosshrc
cp $HOME/.bashrc $PWD/.bashrc
cp $HOME/.zshrc $PWD/.zshrc

